import puppeteer from "puppeteer";
const BASE="https://app-production-800e.up.railway.app";
const b=await puppeteer.launch({headless:true,args:["--no-sandbox"]});
const p=await b.newPage();
await p.goto(`${BASE}/login`,{waitUntil:"networkidle0"}); await new Promise(r=>setTimeout(r,1000));
await p.evaluate(()=>{const s=(el,v)=>{const f=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el),'value').set;f.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));};s(document.querySelector('#email'),'prueba@ger.com');s(document.querySelector('#password'),'prueba123');});
await Promise.all([p.waitForNavigation({waitUntil:"networkidle0"}).catch(()=>{}),p.evaluate(()=>document.querySelector('button[type=submit]').click())]);
await new Promise(r=>setTimeout(r,3000));
console.log("path:", new URL(p.url()).pathname);
const err=await p.$eval('p.text-destructive',el=>el.innerText).catch(()=>null);
console.log("error login:", err||"(ninguno)");
const h1=await p.evaluate(()=>document.querySelector('h1')?.innerText);
console.log("h1:", h1);
await b.close();
