import puppeteer from "puppeteer";
const BASE="https://app-production-800e.up.railway.app";
const b=await puppeteer.launch({headless:true,args:["--no-sandbox"]});
const p=await b.newPage();
await p.goto(`${BASE}/login`,{waitUntil:"networkidle0"}); await new Promise(r=>setTimeout(r,800));
await p.evaluate(()=>{const s=(el,v)=>{const f=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el),'value').set;f.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));};s(document.querySelector('#email'),'prueba@ger.com');s(document.querySelector('#password'),'prueba123');});
await Promise.all([p.waitForNavigation({waitUntil:"networkidle0"}).catch(()=>{}),p.evaluate(()=>document.querySelector('button[type=submit]').click())]);
await new Promise(r=>setTimeout(r,2000));
await p.goto(`${BASE}/identidad`,{waitUntil:"networkidle0"}); await p.waitForSelector('#logo'); await new Promise(r=>setTimeout(r,1200));
const before=await p.evaluate(()=>({p:document.querySelector('#colorPrimary').value,a:document.querySelector('#colorAccent').value}));
const input=await p.$('#logo'); await input.uploadFile('/Users/valentindoroszuk/Downloads/dorvia.png');
await new Promise(r=>setTimeout(r,3000));
const after=await p.evaluate(()=>({p:document.querySelector('#colorPrimary').value,a:document.querySelector('#colorAccent').value,hint:!!Array.from(document.querySelectorAll('p')).find(x=>/Paleta sugerida/.test(x.innerText))}));
console.log("PROD antes:",JSON.stringify(before),"-> después:",JSON.stringify(after));
console.log("cambió la paleta:", before.p!==after.p, "| hint:", after.hint);
await b.close();
