import puppeteer from "puppeteer";
const BASE = "https://app-production-800e.up.railway.app";
const b = await puppeteer.launch({ headless: true, args: ["--no-sandbox"] });
const p = await b.newPage(); await p.setViewport({width:1100,height:800});
await p.goto(`${BASE}/login`, { waitUntil: "networkidle0" });
await new Promise(r=>setTimeout(r,1000));
await p.evaluate(()=>{ const s=(el,v)=>{const f=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el),'value').set;f.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));}; s(document.querySelector('#email'),'prueba@ger.com'); s(document.querySelector('#password'),'prueba123'); });
await Promise.all([p.waitForNavigation({waitUntil:"networkidle0"}).catch(()=>{}), p.evaluate(()=>document.querySelector('button[type=submit]').click())]);
await new Promise(r=>setTimeout(r,2500));
await p.goto(`${BASE}/identidad`, { waitUntil: "networkidle0" });
await new Promise(r=>setTimeout(r,2000));
await p.screenshot({ path: "/tmp/prod-identidad.png" });
console.log("ok", new URL(p.url()).pathname);
await b.close();
